# Generated by Django 4.0.1 on 2022-02-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_movie_likes_alter_movie_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='kinopoisk_rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг Кинопоиск'),
        ),
    ]
