# Generated by Django 4.0.1 on 2022-02-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0004_rename_url_category_slug_rename_url_genre_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.FloatField(default=0, verbose_name='Продолжительность'),
        ),
    ]
