# Generated by Django 4.0.1 on 2022-02-18 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0005_movie_running_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
