# Generated by Django 4.0.1 on 2022-02-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0008_reviews_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='star',
        ),
        migrations.AddField(
            model_name='rating',
            name='count_reviews',
            field=models.IntegerField(default=0, verbose_name='Кол-во оценок'),
        ),
        migrations.AddField(
            model_name='rating',
            name='sum_rating',
            field=models.BigIntegerField(default=0, verbose_name='Кол-во звезд'),
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
