# Generated by Django 4.0.1 on 2022-02-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0009_remove_rating_star_rating_count_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='avg_rating',
            field=models.IntegerField(default=0, verbose_name='Средняя оценка'),
        ),
    ]
