# Generated by Django 4.0.1 on 2022-02-22 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0010_rating_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='likes',
        ),
        migrations.AddField(
            model_name='movie',
            name='review_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_movie', to='web_site.rating', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='avg_rating',
            field=models.FloatField(default=0, verbose_name='Средняя оценка'),
        ),
    ]
