# Generated by Django 4.0.1 on 2022-02-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0011_remove_movie_likes_movie_review_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review_rating',
        ),
    ]
