# Generated by Django 4.0.1 on 2022-02-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0012_remove_movie_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='review_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_movie', to='web_site.rating', verbose_name='Рейтинг'),
        ),
    ]
