# Generated by Django 4.0.1 on 2022-03-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0014_remove_movie_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='Оценка пользователя'),
        ),
    ]
