# Generated by Django 4.0.1 on 2022-03-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0016_actor_description_en_actor_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(default=None, max_length=200),
        ),
    ]
