# Generated by Django 4.0.1 on 2022-03-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0017_alter_actor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
