# Generated by Django 4.0.1 on 2022-03-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0018_alter_actor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='fees_in_usa',
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='сумма в долларах', verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fess_in_world',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='сумма в долларах', verbose_name='Сборы в мире'),
        ),
    ]
