# Generated by Django 4.0.1 on 2022-03-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0019_remove_movie_fees_in_usa_alter_movie_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='ip',
        ),
    ]
