# Generated by Django 4.0.1 on 2022-03-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0020_remove_rating_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='ip',
            field=models.CharField(default=0, max_length=15, verbose_name='IP адрес'),
        ),
    ]
