# Generated by Django 4.0.1 on 2022-03-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0021_reviews_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='kinopoisk_id',
            field=models.IntegerField(default=0, verbose_name='Кинопоиск ID'),
        ),
    ]
