# Generated by Django 4.0.3 on 2022-04-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0023_alter_movie_kinopoisk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='kinopoisk_id',
            field=models.IntegerField(unique=True, verbose_name='Кинопоиск ID'),
        ),
    ]
